# Generated by Django 5.2.11 on 2026-04-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_sla'),
    ]

    operations = [
        migrations.AddField(
            model_name='sla',
            name='current_stage',
            field=models.IntegerField(choices=[(0, 'Requirements & Baselining'), (1, 'Negotiation & Drafting'), (2, 'Implementation & Tooling'), (3, 'Operations & Monitoring'), (4, 'Reporting & Audit'), (5, 'Billing & Renewal')], default=0),
        ),
        migrations.AddField(
            model_name='sla',
            name='scope',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
