# Generated by Django 5.2.11 on 2026-04-19 17:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_sla_current_stage_sla_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='email_message_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_from_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sla',
            name='last_reminder_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sla',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='client_requested_timeline',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='current_stage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='last_activity_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='progress_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('pending_client', 'Pending Client Response'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('reopened', 'Reopened'), ('escalated', 'Escalated')], default='open', max_length=20),
        ),
        migrations.CreateModel(
            name='EmailToTicketMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_message_id', models.CharField(max_length=255, unique=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_mappings', to='tickets.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='EscalationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escalated_from', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('pending_client', 'Pending Client Response'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('reopened', 'Reopened'), ('escalated', 'Escalated')], max_length=50)),
                ('escalated_to', models.CharField(default='escalated', max_length=50)),
                ('reason', models.TextField()),
                ('escalated_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('escalated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_history', to='tickets.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='TicketDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField()),
                ('reminder_sent_24h', models.BooleanField(default=False)),
                ('reminder_sent_1h', models.BooleanField(default=False)),
                ('reminder_sent_overdue', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deadline_tracker', to='tickets.ticket')),
            ],
        ),
    ]
