# Generated by Django 5.2.11 on 2026-04-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_message_email_message_id_message_is_from_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_internal',
            field=models.BooleanField(default=False),
        ),
    ]
