# Generated by Django 5.2.11 on 2026-05-01 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_message_is_internal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='custom_resolution_hours',
            field=models.IntegerField(blank=True, help_text='Custom resolution time in hours for this ticket', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_overdue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='last_time_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='overdue_notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='time_spent_hours',
            field=models.FloatField(default=0, help_text='Total time spent on this ticket in hours'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='warning_notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EngineerFailedTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('failed_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by_admin', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failed_tickets', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failed_assignments', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-failed_at'],
                'unique_together': {('engineer', 'ticket')},
            },
        ),
    ]
