# Generated by Django 5.2.11 on 2026-05-01 13:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_ticket_custom_resolution_hours_ticket_is_overdue_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sla',
            name='assigned_engineers',
            field=models.ManyToManyField(blank=True, related_name='assigned_slas', to=settings.AUTH_USER_MODEL),
        ),
    ]
